### PR TITLE
Try to merge Issue1 to main

### PR DESCRIPTION
**Pull request by techieforgood**
GitHub say's can't merge automatically.

image

### CODE REVIEW

**Comment by techieforgood** [comment]
Hi Bhavya. Can you solve the conflicts and update the repo ?

**Comment by techieforgood** [comment]
I think you have to generate the md files again, since they should contain your changes and my changes.

**Comment by bparikh99** [comment]
I have done the merge please check out main branch Thanks!

**Comment by techieforgood** [comment]
Got it !

**Pull request closed without merging**
